### ISSUE TITLE
Problem about "torchsparse_cuda"

### ISSUE THREAD

**Issue by bdfbdf321** [mit-han-lab/e3d#14]
Hi! Thanks for your wonderful work!
      I meet a problem when testing pretrained model. 
      I installed "torchsparse" correctly but could not import "torchsparse_cuda".
      Could you help me with the problem?

**Comment by kentangSJTU** [comment]
Hi,

Did you directly run our provided command and get into such error? 

Best,
Haotian

**Comment by bdfbdf321** [comment]
Hi.
yes, I run provided command and now the error is 
" x = self.forward(x)"
  x0 = initial_voxelize(z, self.pres, self.vres)
  pc_hash = spf.sphash(torch.floor(new_float_coord).int())
  return hash_gpu(idx)
  return torchsparse_cuda.hash_forward(idx.contiguous())

"AttributeError: module 'torchsparse_cuda' has no attribute 'hash_forward'"

**Comment by bdfbdf321** [comment]
Hi!
Thanks for replying! I am sure there is one GPU on my machine.
I think maybe there is a problem with installing lib "torchsparse_cuda", 
resulting "torchsparse_cuda.hash_forward(idx.contiguous())" error. 
But I can't find out it yet.

**Comment by kentangSJTU** [comment]
Hi,

Sorry for the delayed response because I was working on an exam in the past two days. I revisited the [setup.py](https://github.com/mit-han-lab/torchsparse/blob/master/setup.py) of our `torchsparse` library, and thought it was possible that the GPU backend is not built during your installation. To verify this, you may rerun the installation script for `torchsparse` and check whether there's some building log for `.cu` files.

If there's not, would you mind checking whether the `CUDA_HOME` variable is set on your machine (in the `~/.bashrc` file typically if you are using Ubuntu OS) and add it if it's not?


Thanks,
Haotian

**Comment by bdfbdf321** [comment]
Hi，
Sorry for the delayed response ! I had tried installing the lib for several time and finally succeeded.
Thanks for your patience with my problem!
Best wishes !
